### ISSUE TITLE
Needs information to do expansions but there are no expansions

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/maestro#147]
The specification does not contain any expansions, yet I get the following error on interpretation:

13:57:17.701 [main] INFO  org.intocps.maestro.parser.MablParserUtil - Parting file: wt-example.mabl
13:57:17.828 [main] DEBUG org.intocps.maestro.Mabl - Frameworks: []
Exception in thread "main" java.lang.Exception: Framework annotations required for expansion. Please specify: '@Framework' and '@FrameworkConfig'
	at org.intocps.maestro.Mabl.expand(Mabl.java:123)
	at org.intocps.maestro.Main.main(Main.java:162)

```
simulation
{
    real START_TIME = 0.0;
    real END_TIME = 10.0;
    real STEP_SIZE = 0.1;

    // #############################
    // DataWriter for results
    // #############################
    DataWriter dataWriter = load("DataWriter");
    string[] data_headers[1] = {"crtlValveState","wtLevel"};
    DataWriterConfig dataWriterConfiguration = dataWriter.writeHeader(data_headers);
    string[] data_values[2];

    // #############################
    // Load the FMUs and instantiate instances
    // #############################
    FMI2 tankController = load("FMI2", "{8c4e810f-3df3-4a00-8276-176fa3c9f000}", "watertankcontroller-c.fmu");
    FMI2 singleWatertank = load("FMI2", "{cfc65592-9ece-4563-9705-1581b6e7071c}",  "singlewatertank-20sim.fmu");
    FMI2Component crtlInstance = tankController.instantiate("crtlInstance", false, false);
    FMI2Component wtInstance = singleWatertank.instantiate("wtInstance", false, false);

    wtInstance.setupExperiment(false, 0.0, START_TIME, true, END_TIME);
    crtlInstance.setupExperiment(false, 0.0, START_TIME, true, END_TIME);

    // #############################
    // Set maximum level and minimum level parameters
    // #############################
    real[] crtlParameters[2] = { 2.0 , 1.0 };
    uInt[] crtlParameterValRefs[2] = { 0 , 1 };
    crtlInstance.setReal(crtlParameterValRefs, 2, crtlParameters);

    wtInstance.enterInitializationMode();
    crtlInstance.enterInitializationMode();


    uInt[] crtlValveStateValRef[1] = { 4 };
    bool[] crtlValveStateOutput[1];

    uInt[] crtlLevelInputValRef[1] = { 3 };
    real[] crtlLevelInputValue[1];

    uInt[] wtValveStateValRef[1] = { 16 };
    real[] wtValveStateInputs[1];

    uInt[] wtLevelValRef[1] = { 17 };
    real[] wtLevelOutputValue[1];

    // #############################
    // Perform the Initialization:
    // 1. Extract valve state from controller
    // 2. Convert the valve state from boolean to real
    // 3. Set the valve state on the tank
    // 4. Extract the level from the tank
    // 5. Set the level on the controller
    // #############################
    crtlInstance.getBoolean(crtlValveStateValRef, 1, crtlValveStateOutput);
    real wtValveStateInput;
    if( crtlValveStateOutput[0] )
    {
        wtValveStateInput = 1.0;
    }
    else
    {
        wtValveStateInput = 0.0;
    }


    wtValveStateInputs[0] = wtValveStateInput;
    wtInstance.setReal(wtValveStateValRef, 1, wtValveStateInputs);

    wtInstance.getReal(wtLevelValRef, 1, wtLevelOutputValue);
    crtlInstance.setReal(crtlLevelInputValRef, 1, wtLevelOutputValue);

    wtInstance.exitInitializationMode();
    crtlInstance.exitInitializationMode();

    // #############################
    // Get the valve state from the controller
    // Get the level from the tank 
    // Write the valve state and the water level to the results
    // #############################
    crtlInstance.getBoolean(crtlValveStateValRef, 1, crtlValveStateOutput);
    wtInstance.getReal(wtLevelValRef, 1, wtLevelOutputValue);
    data_values[0] = crtlValveStateOutput[0];
    data_values[1] = wtLevelOutputValue[0];
    dataWriter.writeDataPoint(dataWriterConfiguration, START_TIME, data_values);


    real time = START_TIME;
    // #############################
    // Simulation Loop until END_TIME
    // #############################
    while(time + STEP_SIZE <= END_TIME)
    {
        // #############################
        // Convert valve state from boolean to real
        // #############################
        if( crtlValveStateOutput[0] )
        {
            wtValveStateInput = 1.0;
        }
        else
        {
            wtValveStateInput = 0.0;
        }
        // #############################
        // Set the valve state on the tank
        // Set the level on the controller
        // #############################
        wtValveStateInputs[0] = wtValveStateInput;
        wtInstance.setReal(wtValveStateValRef, 1, wtValveStateInputs);
        crtlInstance.setReal(crtlLevelInputValRef, 1, wtLevelOutputValue);

        // #############################
        // Step the tank
        // Step the controller
        // #############################
        wtInstance.doStep(time, STEP_SIZE, true);
        crtlInstance.doStep(time, STEP_SIZE, true);

        // #############################
        // Get the valve state from the controller
        // Get the level from the tank
        // #############################
        crtlInstance.getBoolean(crtlValveStateValRef, 1, crtlValveStateOutput);
        wtInstance.getReal(wtLevelValRef, 1, wtLevelOutputValue);

        // #############################
        // Increase the time with STEP_SIZE
        // Write the valve state and the water level to the results
        // #############################
        time = time + STEP_SIZE;
        data_values[0] = crtlValveStateOutput[0];
        data_values[1] = wtLevelOutputValue[0];
        dataWriter.writeDataPoint(dataWriterConfiguration, time, data_values);

    }
    
    // #############################
    // Clean up
    // #############################
    dataWriter.close();
    wtInstance.terminate();
    crtlInstance.terminate();
    tankController.freeInstance(crtlInstance);
    singleWatertank.freeInstance(wtInstance);

    unload(tankController);
    unload(singleWatertank);
    unload(dataWriter);
}
```

**Comment by lausdahl** [comment]
fixed in aaf4de2ea6bd62a1aba232c57989d6c212838dba
