### ISSUE TITLE
Problem with URL generation in InitializePluginTest

### ISSUE THREAD

**Issue by nickbattle** [INTO-CPS-Association/maestro#51]
If you install maestro in a location that includes a space in the pathname, then the InitializePluginTest fails during a mvn test:
```
Caused by: java.net.URISyntaxException: Illegal character in path at index 18: /home/nick/Digital Twins/INTO-CPS-Association/maestro/maestro/src/test/resources/watertankcontroller-c.fmu
        at java.net.URI$Parser.fail(URI.java:2913) ~[?:?]
        at java.net.URI$Parser.checkChars(URI.java:3084) ~[?:?]
        at java.net.URI$Parser.parseHierarchical(URI.java:3166) ~[?:?]
        at java.net.URI$Parser.parse(URI.java:3125) ~[?:?]
        at java.net.URI.<init>(URI.java:600) ~[?:?]
        at org.intocps.orchestration.coe.json.InitializationMsgJson.getFmuFiles(InitializationMsgJson.java:219) ~[coe-1.0.10.jar:?]
        ... 42 more
```
The problem is that a URI is created directly from the string of the pathname. What we need is to create the URI via a File that is created from the pathname. That will then correctly "quote" the special characters in the URI. Something like:
```
new File(path).toURI()
```
```

**Comment by CThuleHansen** [comment]
After some digging it seems that this is due to some bug in Maestro1, so I have relabeled it. 
@SimplisticCode is currently working on a new initializer plugin for maestro2.
For this reason I would like to avoid spending to much time on it, as it is soon to be legacy. @nickbattle can you work around it for now?

**Comment by CThuleHansen** [comment]
After more digging, it was solved :)

**Comment by CThuleHansen** [comment]
Too fast, caused a new issue..
